# gifts_data.py - Static gift definitions for validation
GIFTS = [
    # Everyday Gifts
    {"id": "rose", "emoji": "🌹", "name": "Rose", "price": 5, "category": "everyday", "season": None},
    {"id": "chocolate_box", "emoji": "🍫", "name": "Chocolate Box", "price": 10, "category": "everyday", "season": None},
    {"id": "teddy_bear", "emoji": "🧸", "name": "Teddy Bear", "price": 15, "category": "everyday", "season": None},
    {"id": "balloon", "emoji": "🎈", "name": "Balloon", "price": 3, "category": "everyday", "season": None},
    {"id": "flower_bouquet", "emoji": "💐", "name": "Flower Bouquet", "price": 8, "category": "everyday", "season": None},
    {"id": "coffee", "emoji": "☕", "name": "Coffee", "price": 6, "category": "everyday", "season": None},
    {"id": "cookie_jar", "emoji": "🍪", "name": "Cookie Jar", "price": 9, "category": "everyday", "season": None},
    {"id": "wine_glass", "emoji": "🍷", "name": "Wine Glass", "price": 18, "category": "everyday", "season": None},
    {"id": "pizza_slice", "emoji": "🍕", "name": "Pizza Slice", "price": 12, "category": "everyday", "season": None},
    {"id": "cupcake", "emoji": "🧁", "name": "Cupcake", "price": 13, "category": "everyday", "season": None},
    {"id": "lucky_clover", "emoji": "☘️", "name": "Lucky Clover", "price": 7, "category": "everyday", "season": None},
    {"id": "lucky_dice", "emoji": "🎲", "name": "Lucky Dice", "price": 8, "category": "everyday", "season": None},
    {"id": "lady_beetle", "emoji": "🐞", "name": "Lady Beetle", "price": 4, "category": "everyday", "season": None},
    {"id": "candy", "emoji": "🍬", "name": "Candy", "price": 8, "category": "everyday", "season": None},
    {"id": "lollipop", "emoji": "🍭", "name": "Lollipop", "price": 10, "category": "everyday", "season": None},
    {"id": "beer", "emoji": "🍻", "name": "Beer", "price": 15, "category": "everyday", "season": None},
    {"id": "beginner", "emoji": "🔰", "name": "Beginner", "price": 1, "category": "everyday", "season": None},

    # Halloween
    {"id": "jack_o_lantern", "emoji": "🎃", "name": "Jack‑o’‑Lantern", "price": 8, "category": "halloween", "season": "halloween"},
    {"id": "friendly_ghost", "emoji": "👻", "name": "Friendly Ghost", "price": 12, "category": "halloween", "season": "halloween"},
    {"id": "bat_charm", "emoji": "🦇", "name": "Bat Charm", "price": 6, "category": "halloween", "season": "halloween"},
    {"id": "spidey_web", "emoji": "🕸️", "name": "Spidey Web", "price": 5, "category": "halloween", "season": "halloween"},
    {"id": "mage", "emoji": "🧙", "name": "Mage", "price": 15, "category": "halloween", "season": "halloween"},
    {"id": "magic_wand", "emoji": "🪄", "name": "Magic Wand", "price": 11, "category": "halloween", "season": "halloween"},
    {"id": "fairy", "emoji": "🧚‍♂️", "name": "Fairy", "price": 16, "category": "halloween", "season": "halloween"},
    {"id": "vampire", "emoji": "🧛", "name": "Vampire", "price": 19, "category": "halloween", "season": "halloween"},
    {"id": "alien", "emoji": "👽", "name": "Alien", "price": 21, "category": "halloween", "season": "halloween"},

    # Christmas & Winter
    {"id": "christmas_tree", "emoji": "🎄", "name": "Christmas Tree", "price": 20, "category": "christmas", "season": "christmas"},
    {"id": "reindeer_plush", "emoji": "🦌", "name": "Reindeer Plush", "price": 18, "category": "christmas", "season": "christmas"},
    {"id": "snowman", "emoji": "⛄", "name": "Snowman", "price": 10, "category": "christmas", "season": "christmas"},
    {"id": "jingle_bell", "emoji": "🔔", "name": "Jingle Bell", "price": 4, "category": "christmas", "season": "christmas"},
    {"id": "snowflake", "emoji": "❄️", "name": "Snowflake", "price": 7, "category": "christmas", "season": "christmas"},
    {"id": "festive_socks", "emoji": "🧦", "name": "Festive Socks", "price": 9, "category": "christmas", "season": "christmas"},
    {"id": "winter_scarf", "emoji": "🧣", "name": "Winter Scarf", "price": 12, "category": "christmas", "season": "christmas"},
    {"id": "mr_santa", "emoji": "🎅", "name": "Mr. Santa", "price": 25, "category": "christmas", "season": "christmas"},
    {"id": "snowstorm", "emoji": "🌨️", "name": "Snowstorm", "price": 30, "category": "christmas", "season": "christmas"},
    {"id": "love", "emoji": "💕", "name": "Love", "price": 10, "category": "christmas", "season": "christmas"},
    {"id": "champagne_winter", "emoji": "🍾", "name": "Champagne", "price": 27, "category": "christmas", "season": "christmas"},

    # New Year
    {"id": "fireworks_display", "emoji": "🎆", "name": "Fireworks Display", "price": 30, "category": "newyear", "season": "newyear"},
    {"id": "champagne_toast", "emoji": "🥂", "name": "Champagne Toast", "price": 28, "category": "newyear", "season": "newyear"},
    {"id": "party_popper", "emoji": "🎉", "name": "Party Popper", "price": 5, "category": "newyear", "season": "newyear"},
    {"id": "tick_tock", "emoji": "⏳", "name": "Tick‑Tock", "price": 15, "category": "newyear", "season": "newyear"},
    {"id": "champagne_newyear", "emoji": "🍾", "name": "Champagne", "price": 21, "category": "newyear", "season": "newyear"},

    # Summer
    {"id": "beach_paradise", "emoji": "🏖️", "name": "Beach Paradise", "price": 12, "category": "summer", "season": "summer"},
    {"id": "watermelon_slice", "emoji": "🍉", "name": "Watermelon Slice", "price": 6, "category": "summer", "season": "summer"},
    {"id": "sunglasses", "emoji": "🕶️", "name": "Sunglasses", "price": 18, "category": "summer", "season": "summer"},
    {"id": "surfboard", "emoji": "🏄", "name": "Surfboard", "price": 14, "category": "summer", "season": "summer"},
    {"id": "tropical_cocktail", "emoji": "🍹", "name": "Tropical Cocktail", "price": 10, "category": "summer", "season": "summer"},
    {"id": "seashell", "emoji": "🐚", "name": "Seashell", "price": 8, "category": "summer", "season": "summer"},
    {"id": "sun_lotion", "emoji": "🧴", "name": "Sun Lotion", "price": 11, "category": "summer", "season": "summer"},
    {"id": "sunflower", "emoji": "🌻", "name": "Sunflower", "price": 14, "category": "summer", "season": "summer"},
    {"id": "cherry_blossom", "emoji": "🌸", "name": "Cherry Blossom", "price": 15, "category": "summer", "season": "summer"},
    {"id": "cocktail", "emoji": "🍸", "name": "Cocktail", "price": 13, "category": "summer", "season": "summer"},
    {"id": "sunny_day", "emoji": "🌞", "name": "Sunny Day", "price": 20, "category": "summer", "season": "summer"},
    {"id": "tropical_fish", "emoji": "🐠", "name": "Tropical Fish", "price": 17, "category": "summer", "season": "summer"},
    {"id": "palm_tree", "emoji": "🌴", "name": "Palm Tree", "price": 26, "category": "summer", "season": "summer"},
    {"id": "tropical_flower", "emoji": "🌺", "name": "Tropical Flower", "price": 31, "category": "summer", "season": "summer"},
    {"id": "ice_cream", "emoji": "🍦", "name": "Ice Cream", "price": 21, "category": "summer", "season": "summer"},
    {"id": "doughnut", "emoji": "🍩", "name": "Doughnut", "price": 14, "category": "summer", "season": "summer"},
    {"id": "ice_cube", "emoji": "🧊", "name": "Ice Cube", "price": 6, "category": "summer", "season": "summer"},
    {"id": "heatwave", "emoji": "🥵", "name": "Heatwave", "price": 21, "category": "summer", "season": "summer"},
    {"id": "thunderstorm", "emoji": "⛈️", "name": "Thunderstorm", "price": 22, "category": "summer", "season": "summer"},
    {"id": "fruit_juice", "emoji": "🍹", "name": "Fruit Juice", "price": 17, "category": "summer", "season": "summer"},
    {"id": "grape", "emoji": "🍇", "name": "Grape", "price": 19, "category": "summer", "season": "summer"},

    # Spring & Easter
    {"id": "tulip_bulb", "emoji": "🌷", "name": "Tulip Bulb", "price": 6, "category": "spring", "season": "spring"},
    {"id": "baby_chick", "emoji": "🐣", "name": "Baby Chick Plush", "price": 11, "category": "spring", "season": "spring"},
    {"id": "decorated_egg", "emoji": "🥚", "name": "Decorated Egg", "price": 5, "category": "spring", "season": "spring"},
    {"id": "rainbow_wish", "emoji": "🌈", "name": "Rainbow Wish", "price": 20, "category": "spring", "season": "spring"},
    {"id": "bunny", "emoji": "🐰", "name": "Bunny", "price": 9, "category": "spring", "season": "spring"},
    {"id": "seedling", "emoji": "🌱", "name": "Seedling", "price": 15, "category": "spring", "season": "spring"},
    {"id": "easter_basket", "emoji": "🧺", "name": "Easter Basket", "price": 18, "category": "spring", "season": "spring"},
    {"id": "butterfly", "emoji": "🦋", "name": "Butterfly", "price": 5, "category": "spring", "season": "spring"},
    {"id": "new_beginnings", "emoji": "🕊️", "name": "New Beginnings", "price": 25, "category": "spring", "season": "spring"},
    {"id": "swan", "emoji": "🦢", "name": "Swan", "price": 31, "category": "spring", "season": "spring"},
    {"id": "rabbit", "emoji": "🐇", "name": "Rabbit", "price": 12, "category": "spring", "season": "spring"},

    # Fun Gifts
    {"id": "boss_move", "emoji": "😎", "name": "Boss Move", "price": 50, "category": "fun", "season": None},
    {"id": "innocence", "emoji": "🥺", "name": "Innocent", "price": 12, "category": "fun", "season": None},
    {"id": "angelic", "emoji": "😇", "name": "Angelic", "price": 15, "category": "fun", "season": None},
    {"id": "hug", "emoji": "🫂", "name": "Hug", "price": 15, "category": "fun", "season": None},
    {"id": "gold_medal", "emoji": "🥇", "name": "Gold Medal", "price": 100, "category": "fun", "season": None},
    {"id": "silver_medal", "emoji": "🥈", "name": "Silver Medal", "price": 75, "category": "fun", "season": None},
    {"id": "bronze_medal", "emoji": "🥉", "name": "Bronze Medal", "price": 50, "category": "fun", "season": None},
    {"id": "zen_moment", "emoji": "🧘", "name": "Zen Moment", "price": 18, "category": "fun", "season": None},
    {"id": "on_fire", "emoji": "🔥", "name": "On Fire", "price": 40, "category": "fun", "season": None},
    {"id": "sparkle_aura", "emoji": "✨", "name": "Sparkle Aura", "price": 35, "category": "fun", "season": None},
    {"id": "rocket_launch", "emoji": "🚀", "name": "Rocket Launch", "price": 60, "category": "fun", "season": None},
    {"id": "bullseye", "emoji": "🎯", "name": "Bullseye", "price": 28, "category": "fun", "season": None},
    {"id": "handshake", "emoji": "🤝", "name": "Handshake", "price": 10, "category": "fun", "season": None},
    {"id": "fist_bump", "emoji": "🤜🤛", "name": "Fist Bump", "price": 21, "category": "fun", "season": None},
    {"id": "rising_star", "emoji": "📈", "name": "Rising Star", "price": 18, "category": "fun", "season": None},
    {"id": "disco_fever", "emoji": "🪩", "name": "Disco Fever", "price": 20, "category": "fun", "season": None},

    # Overpriced / Prestige Gifts
    {"id": "crown_appreciation", "emoji": "👑", "name": "Crown of Appreciation", "price": 500, "category": "overpriced", "season": None},
    {"id": "developer_trophy", "emoji": "🏆", "name": "Developer Trophy", "price": 999, "category": "overpriced", "season": None},
    {"id": "double_diamond", "emoji": "💎💎", "name": "Double Diamond", "price": 1500, "category": "overpriced", "season": None},
    {"id": "supernova_star", "emoji": "🌟", "name": "Supernova Star", "price": 2000, "category": "overpriced", "season": None},
    {"id": "golden_unicorn", "emoji": "🦄", "name": "Golden Unicorn", "price": 3000, "category": "overpriced", "season": None},
    {"id": "trident_glory", "emoji": "🔱", "name": "Trident of Glory", "price": 4200, "category": "overpriced", "season": None},
    {"id": "saturn", "emoji": "🪐", "name": "Saturn", "price": 5000, "category": "overpriced", "season": None},
    {"id": "infinite_thanks", "emoji": "♾️", "name": "Infinite Thanks", "price": 10000, "category": "overpriced", "season": None},
    {"id": "singularity_orb", "emoji": "🌀", "name": "Singularity Orb", "price": 15000, "category": "overpriced", "season": None},
    {"id": "galactic_fireworks", "emoji": "🎇", "name": "Galactic Fireworks", "price": 20000, "category": "overpriced", "season": None},
    {"id": "legendary_clover", "emoji": "🍀", "name": "Legendary Four‑Leaf Clover", "price": 30000, "category": "overpriced", "season": None},
    {"id": "mind_blown", "emoji": "🤯", "name": "Mind‑Blown Ultimate", "price": 50000, "category": "overpriced", "season": None},
    {"id": "diamond_skull", "emoji": "💀", "name": "Diamond Skull", "price": 100000, "category": "overpriced", "season": None},
    {"id": "tornado_riches", "emoji": "🌪️", "name": "Tornado of Riches", "price": 12000, "category": "overpriced", "season": None},
]
